# Specify the address of your local Docker registry
local_registry = 'localhost:5001' 

# Kubernetes YAML with Kustomize
k8s_yaml(kustomize('kustomize/overlays/dev'))

# Docker Image Build and Push
docker_build(
    'localhost:5001/webapp',
   '.',  
    dockerfile='Dockerfile',
    only=['./'],)

#docker('tag', 'webapp:1.2', 'local_registry/webapp:1.2')



#k8s_resource('dev-web-app', port_forwards=8085)