apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - name: http
      nodePort: 30950
      protocol: TCP
      port: 8080

