name: Build and Push Docker Image

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted # You can choose another runner, if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Build and tag Docker image
        run: |
          echo $pwd
          cd \C:\Users\Geico\actions-runner\_work\Zafin\Zafin\my-webapp
          docker build -t koushikdp/webapp:1.2 .
          #docker tag my-docker-image:latest my-dockerhub-username/my-docker-image:version-tag  # Adjust the image name and tag as needed

      - name: Push Docker image to Docker Hub
        run: |
          docker push koushikdp/webapp:1.2  # Adjust the image name and tag as needed
