# name: Build and Push Docker Image

# on:
#   workflow_dispatch: 
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build-and-push:
#     runs-on: self-hosted # You can choose another runner, if needed

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
#       - name: Build and tag Docker image
#         run: |
#           echo $pwd
#           cd \Users\Geico\actions-runner\_work\Zafin\Zafin\my-webapp\
#           docker build -t koushikdp/webapp:1.7 .
#           #docker tag my-docker-image:latest my-dockerhub-username/my-docker-image:version-tag  # Adjust the image name and tag as needed

#       - name: Push Docker image to Docker Hub
#         run: |
#           docker push koushikdp/webapp:1.7  # Adjust the image name and tag as needed



name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_VERSION: 1.7 # Define it at the top level

jobs:
  build-and-push:
    runs-on: self-hosted # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Docker Version in GitHub Actions Workflow
        shell: powershell
        run: |
          (Get-Content .github\workflows\docker-image.yaml).replace('image: koushikdp/webapp:.*$', "image: koushikdp/webapp:${env:DOCKER_VERSION}") | Set-Content .github\workflows\docker-image.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          echo $pwd
          cd \Users\Geico\actions-runner\_work\Zafin\Zafin\my-webapp\
          docker build -t koushikdp/webapp:${env:DOCKER_VERSION} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push koushikdp/webapp:${env:DOCKER_VERSION}

      - name: Update Docker Version in kustomize Deployment YAML
        shell: powershell
        run: |
          (Get-Content kustomize\base\deployment.yaml).replace('image: koushikdp/webapp:.*$', "image: koushikdp/webapp:${env:DOCKER_VERSION}") | Set-Content kustomize\base\deployment.yaml

